### ISSUE TITLE
Install Etherpads with other apps ?

### ISSUE THREAD

**Issue by Salamandar** [YunoHost-Apps/etherpad_mypads_ynh#10]
I can't install Etherpads with other pads ? o.O

    An app is already installed on the domain my.domain. Mypads needs a whole domain or subdomain to himself.

**Comment by maniackcrudelis** [comment]
Hi,

As the error says,
"Mypads needs a whole domain or subdomain to himself"
So, to install etherpad with mypads you need a sub-domain to install on it.

It's a limitation of mypads plugin.
