### ISSUE TITLE
upgrade to etherpad 1.8.3 needed

### ISSUE THREAD

**Issue by dosch** [YunoHost-Apps/etherpad_mypads_ynh#100]
Just installed on a fresh Debian 9 VPS with the latest YNH.
I get this error when opening a pad in Chrome:
 
<img width="334" alt="Screenshot 2020-04-29 at 19 47 46" src="https://user-images.githubusercontent.com/5372610/80629104-a5b0cc00-8a52-11ea-87af-7c60bb2f87e5.png">

Also some icons in the menu (alignment left for example) are just empty buttons

**Comment by maniackcrudelis** [comment]
Same for me this evening.
Probably an upgrade of a plugin that does not support backward compatibility...

This will wait until the next testing though, as we're about to release the current one.

**Comment by zamentur** [comment]
1.8.3 have a specific bug with mysql. So i think we need to wait 1.8.4 at least.

https://forum.chatons.org/t/etherpad-1-8-3-et-mysql-attendez-avant-de-faire-la-mise-a-jour/1153

**Comment by Tagadda** [comment]
Is there any way to install an older version of this plugin ?

**Comment by maniackcrudelis** [comment]
`npm install ep_comments_page@0.0.35` if you really want to install the previous version.

Anyway, any fix on this will wait for the next testing, so I guess we could just wait for a fix for the version 1.8.3 and have a testing with it.

**Comment by Tagadda** [comment]
This error happens on every stable install... I guess we could do a small fix on stable for that ?

**Comment by farvardin** [comment]
I have the same, and in addition: "Ep_table_of_contents: Please upgrade to etherpad 1.9 for this plugin to work correctly"
can I disable all plugins? I just need to write notes, I don't need the extra stuff.

**Comment by farvardin** [comment]
I've installed etherpad on a fresh new yunohost instance (no upgrade), and I have the same errors:

![image](https://user-images.githubusercontent.com/477243/82302626-23b12480-99ba-11ea-9a7c-7a51297e1f3f.png)

I've tried to (re)move /var/www/etherpad_mypads/node_modules/ep_table_of_contents/ (I've renamed it), and the whole etherpad won't work without it (there is probably a conf file to modify)

**Comment by farvardin** [comment]
ok, I've found how to get rid of this:
from /var/www/etherpad_mypads/node_modules I've moved those plugins into a /temp folder:

> sudo mv ep_automatic_logut ep_comments_page ep_table_of_contents /temp

(I've also removed the automatic logout which is annoying as hell)

I need to restart the etherpad service:

> sudo service etherpad_mypads restart

and now everything is correct
