### ISSUE TITLE
Avoid 1.8.3

### ISSUE THREAD

**Issue by zamentur** [YunoHost-Apps/etherpad_mypads_ynh#101]
etherpad 1.8.3 contains a specific bug with mysql.

We need to wait 1.8.4 at least.

See https://forum.chatons.org/t/etherpad-1-8-3-et-mysql-attendez-avant-de-faire-la-mise-a-jour/1153

**Comment by Hoppux** [comment]
Hi,

Pas de bol, j'ai fait la mise à jour avant de lire ce post. Me voici planté abev Etherpad. Est-il possible de désinstaller/réinstaller Etherpad par l'interface YKH sans perdre les pads ?

Merci par avance
