### ISSUE TITLE
Strange typing issues on Firefox

### ISSUE THREAD

**Issue by binarydad** [YunoHost-Apps/etherpad_mypads_ynh#117]
Using 1.8.4 of MyPads on YNH, when creating a new pad on FF, I get the following behavior. It's automatically going to the next line in the middle of typing. I'm not hitting enter in the video. I don't get this at all using Chrome/Edge. 

Video: https://cloud.binarydad.com/s/8a9kziC4oQF45Mp

Also, I'm getting the following JS error when typing (again, in FF only):

![image](https://user-images.githubusercontent.com/1760607/93937609-0ee0f680-fcf6-11ea-8934-2f3612fd4522.png)

**Comment by ericgaspar** [comment]
Hello @binarydad , is this a one-off or a permanent problem with Firefox? I ran into the same issue but it stopped and I am unable to reproduce it ...
Plugins are often involved in strange behavior. You might want to try disabling plugins one at a time until Etherpad behaves the right way.

**Comment by binarydad** [comment]
The only thing I can see as a culprit may be uBlock, but disabling that doesn't have an effect. It seems to be accompanied with the JS error, as neither one (the behavior nor the error) show in other browsers. 

Even FF on Android (the new FF) works fine, and that also has uBlock installed as an add-on.

**Comment by ericgaspar** [comment]
I was more talking about Etherpad plugins...

**Comment by binarydad** [comment]
Ok... I've tried another FF browser (which syncs with the one in question) and I'm not getting the JS error, nor am I seeing the typing issues. FFS. Let me dig and will close if necessary.
