### ISSUE TITLE
Échec de l'installation  The user etherpad_mypads was not found

### ISSUE THREAD

**Issue by b01xy** [YunoHost-Apps/etherpad_mypads_ynh#12]
bonjour,

merci pour ce super packaging pour yunohost
un détail : lorsque l'on tente d'installer etherpad_mypads_ynh depuis l'interface graphique de yunohost, il est bien précisé que le mot de passe doit faire entre 8 et 32 caractères, mais même avec moins de 8 caractères, on peut cliquer sur le bouton "installer" et cela génère l'erreur : "Échec de l'installation  The user etherpad_mypads was not found"
je me suis fait avoir plusieurs fois :)

++
benjamin

**Comment by maniackcrudelis** [comment]
Salut,

Euh, alors le message d'erreur je sais pas bien pourquoi il est là. Du moins pourquoi il dit ça...
Pour le mot de passe, il s'avère simplement qu'il n'est pas possible de filtrer le nombre de caractère avant validation. C'est donc le script d'installation qui fait cette vérification.

La taille du mot de passe est une limitation du plugin mypads.
