### ISSUE TITLE
Etherpad mypads plugin is not working for linux FreeBSD server

### ISSUE THREAD

**Issue by sarikatekale** [YunoHost-Apps/etherpad_mypads_ynh#120]
Hello,
I have installed etherpad version 1.8.6, etherpad was working fine before installing mypads plugin, when i installed and restarted etherpad on server it gives  me
DOUBLE SETTLE BUG IN HOOK FUNCTION(plugin: ep_mypads, function name: usr/......./etherpad-lite/node_modules/ep_mypads/hooks:expresconfigure, hook:expressconfigure)

Can anyone please tell me how can I solve this, I want to use this plugin for group pads.

And same plugin which i used on windows works fine....So issue is with linux.

**Comment by sarikatekale** [comment]
Anyone can please help me??

**Comment by ericgaspar** [comment]
@sarikatekale 
Hello,
This seems to be an issue specific to the MyPads plugin and not the etherpad_mypads_ynh installation on YunoHost. You might want to issue this bug and ask for help in the MyPads upstream repository https://framagit.org/framasoft/Etherpad/ep_mypads
