### ISSUE TITLE
Remplacer Abiword par LibreOffice ?

### ISSUE THREAD

**Issue by ldidry** [YunoHost-Apps/etherpad_mypads_ynh#14]
Abiword pose parfois des problèmes à la conversion des pads (je crois même que ça fait planter Etherpad). J'avais même du faire un [plugin](https://framagit.org/framasoft/ep_unoconv) pour utiliser libreoffice à la place. Etherpad propose maintenant nativement l'utilisation de libreoffice.

Ce serait une bonne chose, soit d'utiliser plutôt libreoffice, soit de laisser le choix à l'admin qui installe l'app, avec une petite mention genre `Abiword (plus léger, mais moins stable)`

**Comment by maniackcrudelis** [comment]
Tu peux m'indiquer la taille de libreoffice par rapport à abiword?
Il me semble que j'avais rencontré des problèmes avec ce plugin par contre. [Il est commenté justement](https://github.com/YunoHost-Apps/etherpad_mypads_ynh/blob/master/scripts/remove#L86).

Je suppose qu'il faudrait passer à la version 1.6.1 (Pourquoi je l'ai pas avant d'ailleurs...? Ça date de décembre...!)

**Comment by ldidry** [comment]
Alors oui, c'est sûr que libreoffice sera beaucoup plus lourd qu'abiword.

>  Il me semble que j'avais rencontré des problèmes avec ce plugin par contre. Il est commenté justement.

Euh, t'as pas du mettre le bon lien parce que je ne vois pas le rapport avec mon plugin.

Libreoffice est supporté nativement depuis la 1.6.0 (https://github.com/ether/etherpad-lite/blob/1.6.0/settings.json.template#L99)

**Comment by maniackcrudelis** [comment]
Ça m'apprendra à faire 15 trucs en même temps...
https://github.com/YunoHost-Apps/etherpad_mypads_ynh/blob/master/scripts/install#L215

J'avais pris des notes quand j'ai choisi abiword, il prend 260Mo, Libre office en réclame 400. C'est pas non plus fou la différence.
Je n'avais rien noté sur unoconv, juste que ça ne fonctionnais pas. D'où le choix de abiword.
Mais comme j'exporte pas... Je sais pas si c'est instable...

**Comment by ldidry** [comment]
Bah,quand ça foire (import, export), ça fait foirer etherpad. Je me demande si c'est pas l'export en org qui foirait.

**Comment by Rafi594** [comment]
Je n'arrivais pas à exporter et c'était abiword qui faisait planter etherpad maintenant avec libreoffice l'export fonctionne bien.

Il suffit d'ajouter dans la conf d'etherpad le chemin de soffice

**Comment by maniackcrudelis** [comment]
Et installer unoconv et libreoffice-writer.
Ainsi que le plugin ep_unoconv

**Comment by maniackcrudelis** [comment]
Fixé par https://github.com/YunoHost-Apps/etherpad_mypads_ynh/pull/17
