### ISSUE TITLE
Log grossit indéfiniment

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/etherpad_mypads_ynh#15]
Suite à un reboot, le fichier /var/log/etherpad_mypads/etherpad.log a atteint 1 Go, jusqu'à ce que je stoppe le service. Le log indique en boucle : 

```
bin/run.sh: 1: bin/run.sh: dirname: not found
bin/run.sh: 20: bin/run.sh: id: not found
bin/run.sh: 20: [: Illegal number:
bin/installDeps.sh: 1: bin/installDeps.sh: dirname: not found
bin/installDeps.sh: 12: bin/installDeps.sh: uname: not found
bin/installDeps.sh: 12: [: =: unexpected operator
Please install curl
RESTART!
```

**Comment by maniackcrudelis** [comment]
Oh une issue en français ! Ça devient rare...

Le contenu du log est sans rapport direct avec sa taille. On utilise logrotate pour maintenir la taille du log sous les 100Mo. Mais manifestement, ça ne fonctionne pas comme prévu...
Je regarderais ça pour la prochaine release, qui est en cours

**Comment by maniackcrudelis** [comment]
Fixé par https://github.com/YunoHost-Apps/etherpad_mypads_ynh/commit/a3843b91f44e465d84da74d7ca7b8d8f45b6af2d
