### ISSUE TITLE
xz: (stdin): File format not recognized

### ISSUE THREAD

**Issue by rafoo** [YunoHost-Apps/etherpad_mypads_ynh#16]
Bonjour et merci à vous pour ce paquet,

L'installation binaire échoue sur ma machine (une Raspberry Pi B), pendant qu'elle est occupée à compiler les sources, je copie le message d'erreur :
```
Warning: Computing checksum with sha256sum
Warning: Provided checksum to compare to is empty.
Warning: xz: (stdin): File format not recognized
Warning: tar: Child returned status 1
Warning: tar: Error is not recoverable: exiting now
Warning: Binary download failed, trying source.
```

La troisième ligne laisse penser qu'il manque au paquet une dépendance à un outil capable de décompresser du xz. Pourtant d'après aptitude, le paquet xz-utils est bien installé sur ma machine.

Bien cordialement,

**Comment by maniackcrudelis** [comment]
Cette erreur est lié à la version de node qui n'existe pas sur arm.
Normalement le commit d'il y a une heure devrait avoir corrigé ça.

**Comment by rafoo** [comment]
Merci beaucoup, ça fonctionne !
