### ISSUE TITLE
Warning in upgrade - typo in script ?

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/etherpad_mypads_ynh#169]
Hi there,

Thanks for the maintenance of this package, i's useful and smooth to use ! 

Today I upgraded a server (in latest ynh stable, 4.3.6.3) from 1.8.12-ynh1 to ynh2 and I saw this warning in the logs : 
`Warning: dpkg: warning: version 'v8.0.1' has bad syntax: version number does not start with digit`

The upgrade went well, so I guess it's just a little "mishaps" somewhere, but I thought maybe you didn't see it before...

Keep it on : :smiley_cat:

**Comment by ericgaspar** [comment]
Closing: this is a nodeJS helper issue
