### ISSUE TITLE
Gestion des utilisateurs sur un pad

### ISSUE THREAD

**Issue by mic-rigaud** [YunoHost-Apps/etherpad_mypads_ynh#19]
Bonjour,

J'ai remarque un problème au niveau de la gestion des utilisateurs...
Pour faire simple:

- J'ai créé un pad avec 2 utilisateurs (A et B).
- Je me connecte avec l’utilisateur A, et j'écrit un message dans le pad et dans le tchat. Pour le moment tout vas bien, le message est attribue à l utilisateur A comme on pourrai si attendre.
- Ensuite, je me déconnecte et je me reconnecte avec l utilisateur B
- Je me connecte sur le pad. Et là j'observe quelque chose de très étrange... tous les messages écrit par A son attribué a B. La couleur du surlignage est modifié, et le nom de la personne dans le chat aussi. Bref c'est comme si B avait réalisé toutes les actions de A.

Est-ce que le problème est de ma faute? Ou est-ce un bug?
Si mon explications n'est pas clair, je peux fournir des impressions d'écran.

Merci d'avance pour toute aide,

Version de etherpad: 1.6.1
plugin: ep_align, ep_author_hover, ep_automatic_logut, ep_comments_page, ep_countable, ep_delete_empty_pads, ep_etherpad-lite, ep_font_color, ep_font_family, ep_headings2, ep_markdown, ep_mypads, ep_page_view, ep_spellcheck, ep_subscript_and_superscript, ep_table_of_contents, ep_tables2, ep_user_font_size

**Comment by maniackcrudelis** [comment]
Je constate aussi cette erreur, je remarque aussi qu'à force d'essayer, il finit par ne plus savoir qui a écrit quoi...
Semblerais que ce soit un problème de cookies. Le problème ne produit pas avec un autre navigateur ou en navigation privée.

C'est un problème qu'on rencontre parfois avec le sso de YunoHost, mais dans le cas présent, il n'y a pas d'intégration ldap, donc pas de sso.
Ça semble donc être d'avantage un problème du côté du plugin mypads.

**Comment by mic-rigaud** [comment]
Merci pour ta réponse.
Je vais reporter le problème au près des développeurs du pluggin mypads.

**Comment by ldidry** [comment]
Ça a été fixé dans la 1.4.0, ce paquet utilise la 1.4.5, je pense que ce paquet peut être fermé 🙂
