### ISSUE TITLE
curl | sh in n installation

### ISSUE THREAD

**Issue by Phyks** [YunoHost-Apps/etherpad_mypads_ynh#20]
Hi,

I've just came across [these helpers](https://github.com/YunoHost-Apps/etherpad_mypads_ynh/blob/master/scripts/_common.sh#L98-L221) which were presented as a reference for embedding a Node app in Yunohost.

By quickly going through them, I noticed you are using a `curl | sh` scheme to download and install `n`: https://github.com/YunoHost-Apps/etherpad_mypads_ynh/blob/master/scripts/_common.sh#L118.

[`curl | sh`](https://stackoverflow.com/questions/29382739/why-using-curl-sudo-sh-is-not-advised) scheme is not advisable in general, especially for sensitive stuff such as a Yunohost box.

There is an [alternate (manual) method](https://github.com/mklement0/n-install#manual-installation) described in `n-install` repo, which does basically the same thing but offer the advantage of ensuring the code that will be piped is actually a trustworthy code. This however requires manual update of the script from time to time, but gives a major security boost.

What about using this method instead of the `curl | sh`?

**Comment by maniackcrudelis** [comment]
Hi Phyks.

If I get what you propose, instead of doing that:
> curl -> exec

We should do
> curl;
chmod +x;
exec

As this code is inside a script, where's the difference !?

Eventually, what we can do is use a commit or a release and check its checksum before executing it.
But, in case of failure, it needs a upgrade of yunohost to fix it. We have to discuss about that.

**Comment by Phyks** [comment]
Sorry, my comment was not super clear.

> Eventually, what we can do is use a commit or a release and check its checksum before executing it.
But, in case of failure, it needs a upgrade of yunohost to fix it. We have to discuss about that.

Indeed, I meant to download the `n-install` script and version it in this repo. Then, the YNH team has control over the `install` script, can review it and is sure the code which will be executed is the expected one (that is the same as putting a checksum, just a slightly different approach, both are equally secure I think).

If the `n-install` script changes upstream, this will require an update of this YNH app, but it seems it's not changing very often (apparently about [once every few months](https://github.com/mklement0/n-install/commits/master/bin/n-install)).

**Comment by Phyks** [comment]
Note that you need all the `n-{install,uninstall,update}` locally to prevent from `curl | sh`-ing unknown execs: https://github.com/mklement0/n-install/blob/master/bin/n-install#L743-L762.

**Comment by maniackcrudelis** [comment]
Hi
After discussing about that, we (means I) will rewrite this part of the helper to download a release, verify the checksum, then install.
By this way, we can be sure there no risk of malicious code.

Currently, we don't have Node installed. So we will try the make method.

Except if you want to work on it by yourself of course.
Anyway, thanks for having pointing out that possible issue.

**Comment by Phyks** [comment]
Hi,

> After discussing about that, we (means I) will rewrite this part of the helper to download a release, verify the checksum, then install.

Awesome! Thanks for all the work you are putting on Yunohost!

> Except if you want to work on it by yourself of course.

I've just noticed this while looking at this snippet and giving a hand on the Kresus app, but I am not (yet ?) a Yunhost user, so I'm not sure I can efficiently work on this.

**Comment by maniackcrudelis** [comment]
Ok, no problem, I will work on it soon (just I've a lot of things to do)
And, I hope we will soon can be count on you as a YunoHost user ;)
