### ISSUE TITLE
502 error on reboot

### ISSUE THREAD

**Issue by zamentur** [YunoHost-Apps/etherpad_mypads_ynh#29]
It seems the reboot of yunohost server fail to restart etherpad_mypads service. It might be restarted but before nginx (or after?) did it.

The symptom is a "502 Bad gateway error"

To fix it the user on chat reporting this issues has done:

    systemctl enable etherpad_mypads

But it doesn't work: the service etherpad_mypads is down on each reboot.

**Comment by zamentur** [comment]
It's probably due to this configuration
https://github.com/YunoHost-Apps/etherpad_mypads_ynh/blob/master/conf/systemd.service

**Comment by zamentur** [comment]
We have tried these change:
```
[Unit]
Description=Etherpad-lite, the collaborative editor.
Requires=network.target
After=network.target systemd-user-sessions.service

[Service]
Type=simple
User=etherpad_mypads
Group=etherpad_mypads
ExecStartPre=/opt/node_n/bin/n -q 4
Environment="PATH=/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ExecStart=/var/www/etherpad_mypads/bin/safeRun.sh /var/log/etherpad_mypads/etherpad.log
Restart=always

[Install]
WantedBy=multi-user.target
```
But it seems unsufficient

**Comment by maniackcrudelis** [comment]
I can reproduce that with my own server, which rebooted a few days ago.
Unfortunately, there's nothing about it in my logs. Just that the service fail to start. That's all...

There's even nothing about the starting of the service in the log. That's weird.
Seems it's not about etherpad itself but something around. I guess the service file need some extra line or configuration to wait about another thing. But we have to figure out what is it...

**Comment by maniackcrudelis** [comment]
Please try this commit, https://github.com/YunoHost-Apps/etherpad_mypads_ynh/commit/bfb9aac668ff85a3fd962eb105174e4f9f76520e
It fixes the bug on my VM.
