### ISSUE TITLE
Admin etherpad bloqué par SSO

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/etherpad_mypads_ynh#3]
Le sso empêche la connexion à l'admin d'etherpad.
L'authentification tourne en boucle...

L'admin doit donc rester en skipped_uris en attendant...

La raison de cette erreur m'échappe totalement...

**Comment by anmol26s** [comment]
Does that mean admin can not login with SSO? Sorry I don't understand french.

**Comment by maniackcrudelis** [comment]
That means the admin panel has to be publicly accessible.
It has to stay behind a skipped_uris, otherwise you can't connect to the admin panel.

**Comment by Aeris1One** [comment]
> La raison de cette erreur m'échappe totalement...

Maybe because of the HTML authentication before accessing admin panel ?

**Comment by Aeris1One** [comment]
Anyway, that's a core issue so maybe open a ticket on Yunohost issue ?

**Comment by Tagadda** [comment]
Is this still a thing ? I can't login to `/pad/admin`, it keeps asking me for credentials, even when I provide the good ones.

**Comment by maniackcrudelis** [comment]
On which version of YunoHost ?
Is the app install in public mode or private ?

**Comment by Tagadda** [comment]
I'm using YunoHost 3.7.1.1, and the app is in public mode.

**Comment by maniackcrudelis** [comment]
There's no restriction on the admin panel if you're in public mode.

Are the credentials page from the YunoHost portal or a simple pop-up box asking for credential with a message on top ?

**Comment by Tagadda** [comment]
The pop-up box, similar to a http_basic_auth if I'm correct.
What credentials should I use there ? My Yunohost user, or the one in `/var/www/etherpad_mypads/credentials.json` ?

**Comment by maniackcrudelis** [comment]
The credential from `credentials.json`

Just tried on a VM.
From private browsing, without being connected to YunoHost, it works.
From a session where I'm connected it doesn't work indeed.

I suspect the new wonderful (yet not properly tested...) permission system...

Meanwhile, you can go directly to the admin panel from private browsing.

**Comment by Tagadda** [comment]
This package doesn't use the new permission system yet ? https://github.com/YunoHost-Apps/etherpad_mypads_ynh/issues/98

**Comment by maniackcrudelis** [comment]
Nope indeed, on purpose...
Because I know that feature is not stable, and yet released on stable...

And yet it's actually the cause of the issue https://github.com/YunoHost/issues/issues/1579#issuecomment-620159664

**Comment by Tagadda** [comment]
Ah, this might be related, I guess ?
https://github.com/YunoHost/issues/issues/1420
https://github.com/YunoHost/yunohost/pull/883

**Comment by maniackcrudelis** [comment]
I don't know, but it could indeed.
What bother me right now though, is that the PR to fix that is not yet merged. And it was perfectly working before the new permission system wipe out the previous perfectly working permission system to add a new one not completely tested...

And so, for now, we have no proper solution since the package didn't change the way that problem was managed.

**Comment by tiotrom** [comment]
So almost a year later, is not working...same issue. Not working in private mode either...

**Comment by SiM** [comment]
With latest update, by granting the right permission (etherpad admin), I now have the auth pop-up :+1: 

But authentication doesn't work. (I use credentials set on credentials.json, tried with very simple combination...)
The pop-up is always showing up, despite entering correct credentials, and in the log I got "Failed authentication from IP 127.0.0.1" at each try (I have also this line on the first loading, before entering credentials)

**Comment by ericgaspar** [comment]
Are you using the same password as the one used by the app admin?

**Comment by SiM** [comment]
If do you mean the credentials that were before sent by mail, yes (and I also tried to modify credentials.json by adding others users or change the password, without success)

**Comment by ericgaspar** [comment]
What I mean is that when I register during Etherpad_mypads innstall with the same username/password as for connecting to my YunoHost session I can connect to Eherpad admin page. When I use username/random_password I can't access Etherpad admin page.

**Comment by TROMsite** [comment]
On my end, after the update, I am redirected to the yunohost admin page and that's all. text.trom.tf/admin redirects to that. I login there but makes no difference. Weird.

**Comment by SiM** [comment]
> What I mean is that when I register during Etherpad_mypads innstall with the same username/password as for connecting to my YunoHost session I can connect to Eherpad admin page. When I use username/random_password I can't access Etherpad admin page.

Wow thank you for your message, this is quite tricky :sweat_smile: 
So after changing login/password of credentials.json by those of YNH user, it works well !

**Comment by TROMsite** [comment]
> Wow thank you for your message, this is quite tricky sweat_smile
> So after changing login/password of credentials.json by those of YNH user, it works well !

I did the same, but for me https://text.trom.tf/admin still redirects to https://tromland.nohost.me/yunohost/sso/ - so I cannot even see the login popup. Any idea why? It used to work before the update. Cheers!

**Comment by SiM** [comment]
> I did the same, but for me https://text.trom.tf/admin still redirects to https://tromland.nohost.me/yunohost/sso/ - so I cannot even see the login popup. Any idea why? It used to work before the update. Cheers!

Did you give _etherpad_mypads (admin)_ permission to your user?

**Comment by TROMsite** [comment]
> Did you give _etherpad_mypads (admin)_ permission to your user?

Yes. 

```
 "users": {
    "*******": {
      // 1) "password" can be replaced with "hash" if you install ep_hash_auth
      // 2) please note that if password is null, the user will not be created
      "password": "*****************",
      "is_admin": true
    }
  },
}
```

**Comment by SiM** [comment]
I was referring to the Yunohost permission mechanism ;) (https://yunohost.org/en/groups_and_permissions)

**Comment by TROMsite** [comment]
Aaah ok. It works now. So you have to grand permission in the settings and the config file as well. To use the same user. We had it setup with a different user before as admin, then Etherpad got updated and probably something changed. Works now so that's good. Thanks!
