### ISSUE TITLE
Open an issue on https://framagit.org/framasoft/Etherpad/ep_mypads/issues for SSO

### ISSUE THREAD

**Issue by ldidry** [YunoHost-Apps/etherpad_mypads_ynh#48]
I don't know how you handle the SSO authentication with MyPads, but as there is now a setting to choose the authentication method in MyPads admin settings, you may want to create an issue on https://framagit.org/framasoft/Etherpad/ep_mypads/issues to ask for YNH's SSO integration.

If you do so, please describe all its workflow and how to get 
- login
- first name
- last name
- mail

Those informations are required to create MyPads users.

**Comment by Aeris1One** [comment]
LDAP is already implemented, SSO is only the login by clicking on the tile (without having to type another time your password on MyPads). This app already use LDAP. If I remember well the SSO login uses HTTP Header but not sure.
