### ISSUE TITLE
install issue : ValueError: Unknown format code 's' for object of type 'bool'

### ISSUE THREAD

**Issue by kiwiASRALL** [YunoHost-Apps/etherpad_mypads_ynh#5]
Hi,

I have an issue with your app. Here my command:

```
root@olinux:~# yunohost app install https://github.com/YunoHost-Apps/etherpad_mypads_ynh
Downloading...
Extracting...
Done.
Choose a dedicated domain for Etherpad Mypads.: sub.domain.fr
Choose the Etherpad Mypads administrator (must be an existing YunoHost user): user
Is it a public website? (Yes|No) (default: Yes): 
Set the administrator password: azerty
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/app.py", line 482, in app_install
    if hook_exec(app_tmp_folder + '/scripts/install', args_dict) == 0:
  File "/usr/lib/moulinette/yunohost/hook.py", line 281, in hook_exec
    ask_string += ' (default: {:s})'.format(arg['default'])
ValueError: Unknown format code 's' for object of type 'bool'
Error: An unexpected error occured

```

Do you have an idea how to resolve this ?

Thank you

**Comment by maniackcrudelis** [comment]
Hi,

I have checked the install just now, and I have no error.
After admin password, the manifest asks if you want use abiword, this is a boolean. But in your case, the script crashes at this point.

But I check the install process in french, maybe in english, the manifest is corrupted. I need to reinstall Yunohost in english to check that.

**Comment by maniackcrudelis** [comment]
Hello,

I have checked the package with a english version of yunohost. But I have no errors.
Are you sure your Yunohost is up to date?

**Comment by kiwiASRALL** [comment]
Hi, FYI it was yunohost not up to date. Sorry 

and thank you
