### ISSUE TITLE
Can't install etherpad

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/etherpad_mypads_ynh#59]
Hello,

Every time i try to install it, i have an error. There is my log: https://framabin.org/p/?1df4d0ed4033cade#NXUa33e8eRi1pSD5C34W9cug6xG1kysz/V1/WnNCTwU=

**Comment by maniackcrudelis** [comment]
https://forum.yunohost.org/t/impossible-dinstaller-etherpad/6456/3?u=maniack_crudelis

**Comment by stemy2** [comment]
> https://forum.yunohost.org/t/impossible-dinstaller-etherpad/6456/3?u=maniack_crudelis

This is not the plugin. I unchecked the box «install plugins» and it still doesn't work.
