### ISSUE TITLE
install error:  « ../sources/ajouts/. »

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/etherpad_mypads_ynh#6]
Hi,
I couldn't install your app:
```
Téléchargés : 1 fichiers, 903K en 0,9s (1013 KB/s)
Attention : cp: impossible d'évaluer « ../sources/ajouts/. »: Aucun fichier ou dossier de ce type
Attention : etherpad_mypads install's script has encountered an error. Installation was cancelled.
Attention : Erreur : Échec de l'installation
```
My yunohost is up to date, have you an idea how to resolve this?

Thanks

**Comment by maniackcrudelis** [comment]
Git removes this subdir because is empty... I've added a .gitignore...
You can retry

**Comment by tomdereub** [comment]
Ah, en fait j'avais fait l'installation à partir du dépôt communautaire (yunohost app install etherpad_mypads), et j'ai l'impression que ça n'est pas à jour avec ton dépôt ? Je n'avais pas la question de la langue en tout cas.
En la relançant avec l'url ça a marché sans problème, merci !

**Comment by maniackcrudelis** [comment]
Oui c'est de ma faute, je me suis toujours pas mis dans le crâne que le dépôt est fixé sur un commit. Faut que je mette à jour mes app sur le dépôt !

PS: Mon anglais est si lamentable que ça pour que tu me réponde en français ? Tu as le droit de me dire oui ;)

**Comment by tomdereub** [comment]
Non, c'est juste par pure flemme...
