### ISSUE TITLE
Cannot access pads from nextcloud ownpad plugin

### ISSUE THREAD

**Issue by eauchat** [YunoHost-Apps/etherpad_mypads_ynh#60]
I have etherpads and nextcloud in my yunohost server, and I installed the ownpad nextcloud plugin that allows to create documents that are actually a link to a etherpad or ethercalc, then you can see the pad as an iframe in nextcloud and edit it like if it was a stored document.  

I'm running ethercalc separately (not in yunohost), and it's working properly in nextcloud, but somehow the pads don't, the iframe doesn't load I think, and in the browser's console, there is the following message: `Load denied by X-Frame-Options: https://pad.mydomain.tld/p/myjustnowcreatedpadid does not permit cross-origin framing.`  
At first I thought of submitting the issue to ownpad, but because of this console message, I think the error must come from yunohost etherpad instance that doesn't allow the content to be shown in an iframe maybe? Especially since that if I click on the link to the pad that ownpads display, it shows properly in it's own browser window.  

Any idea where the problem could be coming from, and a way to solve it ?

**Comment by eauchat** [comment]
I'm not sure I understand what you mean. Why would nextcloud nginx config be problematic to the pads in another domain when it doesn't make any problem with calcs in another domain?
I understand very little the nginx config, which part of it you think would be relevant?

**Comment by maniackcrudelis** [comment]
There's no restriction in the config file of etherpad, https://github.com/YunoHost-Apps/etherpad_mypads_ynh/blob/master/conf/nginx.conf, but there's a lot in the one of nextcloud

- https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/conf/nginx.conf#L16-L21
- https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/conf/nginx.conf#L82-L87

So maybe one of those header can block your request.
