### ISSUE TITLE
Password with { character prevent installation

### ISSUE THREAD

**Issue by nqb** [YunoHost-Apps/etherpad_mypads_ynh#61]
YunoHost 3.3.3.

Steps to reproduce: try to install the application with Admin Password like: `bu?a{:Q[*dWM-\7+MA-/`

Actual results: Moulinette error

Expected results: Installation successful

**Comment by nqb** [comment]
After this error, I do a new installation of the application with a more simple password. It works but it seems that provoke this issue https://github.com/YunoHost/issues/issues/1259

**Comment by maniackcrudelis** [comment]
Hi nqb

About this password, there's probably nothing we can do. Too many special characters than can break code, and it's probably what happened here.

About your error with node, can you list your node versions :
```
ls -alh /opt/node_n/n/versions/node/
```

**Comment by maniackcrudelis** [comment]
6.16.0 is the last 6 version, looks like n failed to log something at the line 555, however, node has been correctly installed by n.
I don't know why n failed to its own process. It's probably not related to your previous error.
But, keep us informed if that error happen again for the next upgrade of node.

**Comment by nqb** [comment]
> About this password, there's probably nothing we can do.

Not agree, we can:
1. check password syntax to be sure if doesn't contain special characters
2. prevent users about forbidden characters

But for me, we should support special characters

**Comment by maniackcrudelis** [comment]
The thing is, we can't easily support special characters because those special characters will break bash, sed, or any other script languages used. Here, first '{' is sure to break bash because that's a symbol used to separate variables.
If you find a way to fix that, feel free to do it.

**Comment by Psycojoker** [comment]
Apparently you can use `envsubst` to avoid using sed for that:

```bash
psycojoker@dolgoff /tmp cat test.template                              
password = '${password}'
psycojoker@dolgoff /tmp password='bu?a{:Q[*dWM-\7+MA-/' envsubst < test.template
password = 'bu?a{:Q[*dWM-\7+MA-/'
```

**Comment by maniackcrudelis** [comment]
That isn't just about sed, before sed, a { in a variable will break bash itself.
To support that kind of characters we need a full wrapper around it to prevent any bug anywhere in the code.
Actually, we already have a sed helper that support some special characters (already used by this app), but that's not enough...

**Comment by Psycojoker** [comment]
> That isn't just about sed, before sed, a { in a variable will break bash itself.

Only if you evaluate the variable right? You can uses `print '$s' "$variable"` and that handles having whatever you want in the variable without any problems:

```bash
$ variable='{'          
$ printf '%s' "$variable"
{
```

I used to play with that when I was handling unsafe input in bash some years ago.

**Comment by nqb** [comment]
Ok @maniackcrudelis.

What's your opinion on my two proposals ?

**Comment by maniackcrudelis** [comment]
> - check password syntax to be sure if doesn't contain special characters

You would have to know exactly which characters are going to be a problem. But that's possible.
There's already some verification at the beginning of each install script, you can add one other.

> - prevent users about forbidden characters

Same thing, which characters should be forbidden ?
It can be done, but in the core, not in apps part since that verification should be done just after the password is given by the user.

**Comment by nqb** [comment]
Hello @maniackcrudelis,

Regarding the issue with `node`, I wonder if it's not just a PATH issue because at line 555, `node` is called like this:
```bash
log installed $(node --version)
```
I'm not sure the current PATH permit to find the `node` command.

**Comment by maniackcrudelis** [comment]
For sure it is, somehow n isn't updating the PATH variable correctly or something like that.
But, again, that's n failing during its own process, and here to log the version it has installed. So, it's probably more a problem about n than etherpad.

**Comment by maniackcrudelis** [comment]
The repository is here, https://github.com/tj/n

**Comment by alexAubin** [comment]
Imho this issue can be closed as https://github.com/YunoHost/yunohost/pull/671 should fix the issue
