### ISSUE TITLE
Installdeps fail from clean yunohost

### ISSUE THREAD

**Issue by cl-parsons** [YunoHost-Apps/etherpad_mypads_ynh#66]
Hi,

I tried to install the Etherpad app, with or without myPads, and it always fails.

Seems that the issue comes from the installation of node, or during the installDeps.sh run. May somebody check what's going on?

[Install logs](https://paste.yunohost.org/raw/merefatiso)

**Comment by maniackcrudelis** [comment]
Could you please show me the content of the log `/var/log/etherpad_mypads/installation.log` ?

**Comment by cl-parsons** [comment]
[here it is!](https://nopaste.linux-dev.org/?1195253)

**Comment by cl-parsons** [comment]
node version 6 seems outrageously outdated, don't you think?

**Comment by maniackcrudelis** [comment]
Until recently Etherpad was using node 6,so this package does.

Is there anything else in that log? There's no error so far

**Comment by cl-parsons** [comment]
Nope, the logs are pretty unclear I assume. I'm currently working on the update of this package. That could be nice to see what's going wrong with that!

**Comment by maniackcrudelis** [comment]
If you're idea is to upgrade the version of node, change only the version of node here, https://github.com/YunoHost-Apps/etherpad_mypads_ynh/blob/master/scripts/_variables#L10
That would be enough

**Comment by cl-parsons** [comment]
Ok, beside of the package version problem (see https://github.com/YunoHost-Apps/etherpad_mypads_ynh/pull/67 ), I think that the package may fail to install when the server lacks RAM, due to the npm huge list of packages to install.

This could the point to another issue : alert the user when he may lack RAM to install the node packages.

(i tested with 800Mo RAM, sometimes it work, sometimes it doesn't, but when I put 2G it works everytime. I already had this problem in other VM's without yunohost, with nodejs NPM. I'd advise to use yarn instead ....)
