### ISSUE TITLE
+ CHECK_VAR etherpad_mypads 'app name not set'

### ISSUE THREAD

**Issue by buzzworkers** [YunoHost-Apps/etherpad_mypads_ynh#7]
On dirait bien que l'install oublie de demander le nom qu'on veut donner à l'app : 
- CHECK_VAR etherpad_mypads 'app name not set'
  dans le log d'install...

**Comment by maniackcrudelis** [comment]
Salut,
cette fonction vérifie que la variable $app n'est pas vide. Et affiche en erreur "app name not set" le cas échéant. En cas d'erreur, cette fonction arrête l'installation.

Le label de l'application sur le SSO n'est pas géré par le script d'install. Si tu installes en ligne de commande, tu dois ajouter l'argument -l je crois.
