### ISSUE TITLE
Level dropped to 2 in latest CI

### ISSUE THREAD

**Issue by decentral1se** [YunoHost-Apps/etherpad_mypads_ynh#72]
See https://ci-apps.yunohost.org/ci/job/4278:

```
Warning: yunohost.hook <lambda> - [970.1] Please wait, the service etherpad_mypads is restarting.........................
Error: moulinette.core translate - unable to retrieve key 'service_description_etherpad_mypads' for default locale 'en'
Info:  The service etherpad_mypads has correctly started.
```

Looks like the issue?

**Comment by decentral1se** [comment]
Btw, I'm still able to install this package correctly :+1:

**Comment by maniackcrudelis** [comment]
The error is from the upgrade from an old commit, looks like this commit doesn't like the last version of YunoHost.

**Comment by zamentur** [comment]
This issues has been fixed current level is more higher than 2
