### ISSUE TITLE
colibris plz

### ISSUE THREAD

**Issue by elinahedenius** [YunoHost-Apps/etherpad_mypads_ynh#77]
Would be very nice if the new (soon to be default?) theme, colibris, could be added :)

**Comment by Aeris1One** [comment]
You can add `"skinName": "colibris",` to settings.json to enable the new skin, it works since 1.6, but colibris is default only since 1.8.
However, the config file will be updated and the next release will (surely) include colibris as default skin. (#88)

**Comment by webafrancois** [comment]
Yes, it would be better than the default skin.
Just add it to the settings.json
and restart the etherpad_maypad.service
`systemctl restart etherpad_mypads.service`

**Comment by alexAubin** [comment]
Fixed in latest release o/
