### ISSUE TITLE
Impossible to connect : password "must be between undefined and undefined characters".

### ISSUE THREAD

**Issue by augustindo** [YunoHost-Apps/etherpad_mypads_ynh#8]
Hi,
Thanks for packaging this app for Yunohost !
We've installed it successfully today on 3 internet cubes. We have been able to connect to MyPads, create users, and test the basic features (create folder, pad, share it etc.).
But after a reboot, it's now impossible to connect or to create a new user because we can not enter password, warning says "password "must be between undefined and undefined characters""
![menu_001](https://cloud.githubusercontent.com/assets/20402274/20248309/2d03af0a-a9d9-11e6-98bb-63743f1c63ad.png)

When we go to https://pad.domain.tld/mypads, we can not create "anonymous" pad anymore, we are directly redirected to https://pad.domain.tld/mypads/?/login

It's like a config file is missing, as said here : https://framagit.org/framasoft/ep_mypads/issues/90
We tried to add index.html to the url : we reach the new adress  https://pad.domain.tld/mypads/index.html?/login but the problem is still there.

Finally we can connect to the admin interface but it is buggy too : 
![selection_002](https://cloud.githubusercontent.com/assets/20402274/20248331/cfe9edce-a9d9-11e6-8502-e45ea01715a1.png)

We already tried to reboot or reload nginx.

If you have any idea ... Thanks in advance !

**Comment by maniackcrudelis** [comment]
Wow, it's a difficult problem in appearance.
I need perform some test, but I will test on x86, not arm...

**Comment by maniackcrudelis** [comment]
Ok, I found the problem.

The modification of language cause an issue in the database.
I desactivated the language in the package for the moment. You can reinstall if you want.
Or you can correct the database. Simply add double quotes around the language into the key 'mypads:conf:defaultLanguage' and reboot the service.

**Comment by augustindo** [comment]
Thanks @maniackcrudelis !
I've not tried yet to reinstall the app yet because MyPads still works on 1 cube (but fails on 3 others) and we clone the good one to reinstall the 3 others, so MyPads works on the 4 cubes for now.
