### ISSUE TITLE
Please upgrade to 1.8

### ISSUE THREAD

**Issue by Aeris1One** [YunoHost-Apps/etherpad_mypads_ynh#89]
I saw some PRs about upgrading to 1.7.10, but 1.8 is out.

**Comment by maniackcrudelis** [comment]
https://github.com/YunoHost-Apps/etherpad_mypads_ynh/pull/83 is about mypads plugin

**Comment by Aeris1One** [comment]
o_O
Sorry 😅
But can't you upgrade etherpad as well ?

**Comment by maniackcrudelis** [comment]
The PR you opened recently, https://github.com/YunoHost-Apps/etherpad_mypads_ynh/pull/88, is about the new skin available in 1.8.0
The current testing release is on 1.8.0

**Comment by Aeris1One** [comment]
The package installed 1.7.5 while it's said "Shipped version: 1.8"

**Comment by maniackcrudelis** [comment]
https://github.com/YunoHost-Apps/etherpad_mypads_ynh/blob/testing/conf/app.src#L1

**Comment by Aeris1One** [comment]
Yup, sry for the mistake and this useless ticket 😅
