### ISSUE TITLE
Installation impossible

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/etherpad_mypads_ynh#9]
Salut,
J'ai fait la mise à jour avec sudo yunohost app upgrade --verbose etherpad_mypads -u https://github.com/YunoHost-Apps/etherpad_mypads_ynh et ça a très bien marché. Mais je ne me souvenais plus du mdp admin, du coup je l'ai désinstallé, et maintenant impossible de le ré-installer. J'ai essayé : 

```
sudo yunohost app install etherpad_mypads
Choisissez un domaine dédié pour Etherpad Mypads. : ...
Administrateur du site (doit être un utilisateur YunoHost existant) : ...
Définissez le mot de passe administrateur (entre 8 et 30 caractères) :
Choisissez la langue [en | fr] (default: en) : ...
Est-ce un site public ? [Yes | No] (default: Yes) : ...
Utiliser abiword (~260Mo) pour étendre les possibilités d'export (pdf, doc) ? [0 | 1] (default: 0) : ...
Attention : wget : impossible de résoudre l'adresse de l'hôte « codeload.github.com »
Attention : Corrupt source
Attention : tar: Ceci ne ressemble pas à une archive de type « tar »
Attention :
Attention : gzip: stdin: unexpected end of file
Attention : tar: Child returned status 1
Attention : tar: Error is not recoverable: exiting now
Attention : cp: impossible d'évaluer « etherpad-lite-1.6.0/. »: Aucun fichier ou dossier de ce type
Attention : W: Impossible de récupérer http://ftp.fr.debian.org/debian/dists/jessie/InRelease
Attention :
Attention : W: Impossible de récupérer http://security.debian.org/dists/jessie/updates/InRelease
Attention :
Attention : W: Impossible de récupérer http://ftp.fr.debian.org/debian/dists/jessie-updates/InRelease
Attention :
Attention : W: Impossible de récupérer http://httpredir.debian.org/debian/dists/jessie-backports/InRelease
Attention :
Attention : W: Impossible de récupérer http://repo.yunohost.org/dists/megusta/InRelease
Attention :
Attention : W: Impossible de récupérer http://repo.yunohost.org/debian/dists/jessie/InRelease
Attention :
Attention : W: Impossible de récupérer http://security.debian.org/dists/jessie/updates/Release.gpg  Ne parvient pas à résoudre « security.debian.org »
Attention :
Attention : W: Impossible de récupérer http://ftp.fr.debian.org/debian/dists/jessie/Release.gpg  Ne parvient pas à résoudre « ftp.fr.debian.org »
Attention :
Attention : W: Impossible de récupérer http://ftp.fr.debian.org/debian/dists/jessie-updates/Release.gpg  Ne parvient pas à résoudre « ftp.fr.debian.org »
Attention :
Attention : W: Impossible de récupérer http://repo.yunohost.org/dists/megusta/Release.gpg  Ne parvient pas à résoudre « repo.yunohost.org »
Attention :
Attention : W: Impossible de récupérer http://repo.yunohost.org/debian/dists/jessie/Release.gpg  Ne parvient pas à résoudre « repo.yunohost.org »
Attention :
Attention : W: Impossible de récupérer http://httpredir.debian.org/debian/dists/jessie-backports/Release.gpg  Ne parvient pas à résoudre « httpredir.debian.org »
Attention :
Attention : W: Le téléchargement de quelques fichiers d'index a échoué, ils ont été ignorés, ou les anciens ont été utilisés à la place.
Attention : !!
Attention :   etherpad_mypads install's script has encountered an error. Installation was cancelled.
Attention : !!
Erreur : Échec de l'installation
```

Et avec l'adresse du dépôt : 
```
sudo yunohost app install --verbose https://github.com/YunoHost-Apps/etherpad_mypads_ynh
Téléchargement...
Erreur : unable to download https://github.com/YunoHost-Apps/etherpad_mypads_ynh/archive/master.zip
Erreur : Impossible de récupérer les fichiers sources
```

**Comment by maniackcrudelis** [comment]
Ton problème semble venir de ta connexion internet, le lien https://github.com/YunoHost-Apps/etherpad_mypads_ynh/archive/master.zip fonctionne sans problème.
Essaye un `ping yunohost.org`

**Comment by tomdereub** [comment]
Alors ça c'est vraiment bizarre... J'ai accès à mon serveur (je suis à distance), tous les services marchent, mais un ping me renvoi "unknown host yunohost.org"...
Donc rien à voir avec ton app effectivement, mais il y a un truc que je pige pas...

**Comment by maniackcrudelis** [comment]
Tu utilises dnsmasq?

**Comment by tomdereub** [comment]
Je ne sais pas... pas volontairement en tout cas.

**Comment by tomdereub** [comment]
Mais dans mes services il est noté "en cours d'exécution". Ça sert à quoi ?

**Comment by maniackcrudelis** [comment]
dnsmasq est un cache DNS, toutefois je crois que par défaut il est utilisé par Yunohost.
Peux-tu redémarrer le service dnsmasq dans un premier temps.
Et par la suite vérifier si le port 53 est ouvert sur ta box. Si tu es en upnp, il l'est probablement et il faudra le fermer sur la box.

Si le port est ouvert sur l'extérieur, dnsmasq répond à des requêtes extérieurs et est vite saturé. Il ne répond alors plus aux demandes locales, ce qui provoque des erreurs de résolution DNS, comme celle que tu rencontres.

**Comment by tomdereub** [comment]
Je suis pas chez moi, du coup je peux pas accéder à l'interface de ma box (ou en tout cas je ne sais pas faire en ssh depuis le serveur).
Par contre le port 53 est ouvert dans mon pare-feu yunohost, c'est normal ? et l'upnp est désactivé (sur yunohost, sur la box je sais plus).

**Comment by tomdereub** [comment]
pour info, mon serveur passe par un vpn, donc normalement tout passe par le même port il me semble ?

**Comment by tomdereub** [comment]
et j'ai redémarré dnsmasq, mais ça n'a rien changé.

**Comment by maniackcrudelis** [comment]
Ton port doit être ouvert sur le serveur si tu veux te servir de dnsmasq dans ton réseau local.
Mais si l'upnp est désactivé, les ports ouverts sur la box sont seulement ceux que tu as ouvert toi même.

Je ne connais guère l'usage des vpn.

Essaye donc un `dig yunohost.org` pour voir où ça va. Et un `nslookup yunohost.org` pour voir à qui tu demandes.

**Comment by tomdereub** [comment]
dig yunohost.org

; <<>> DiG 9.9.5-9+deb8u8-Debian <<>> yunohost.org
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by tomdereub** [comment]
nslookup yunohost.org
;; connection timed out; no servers could be reached

**Comment by maniackcrudelis** [comment]
Ah oui... Donc t'as rien qui sort...

Tu peux m'indiquer le contenu de /etc/resolv.conf

**Comment by tomdereub** [comment]
nameserver 80.67.169.12
nameserver 2001:913::8

**Comment by maniackcrudelis** [comment]
Le premier je comprend, mais c'est quoi "2001:913::8" ?

**Comment by tomdereub** [comment]
alors là... c'est pas de l'IPv6 ?

**Comment by maniackcrudelis** [comment]
Ça me semble trop court pour de l'ipv6.
Commente cette ligne, redémarrer dnsmasq et retente un nslookup

**Comment by tomdereub** [comment]
Pas plus de résultat. Pour être sûr, on commente bien avec ; ?

**Comment by maniackcrudelis** [comment]
Non, avec #

**Comment by tomdereub** [comment]
Pareil...

**Comment by maniackcrudelis** [comment]
Essaye un ping sur 80.67.169.12
Ça passe depuis mon serveur.

**Comment by tomdereub** [comment]
Là ça marche.

**Comment by tomdereub** [comment]
Donc c'est vraiment la résolution de noms de domaine qui plante, c'est ça ?

**Comment by tomdereub** [comment]
je me suis mis sur le salon de support yunohost, ça sera plus pratique, si jamais tu veux continuer à m'aider à chercher une solution.
