### ISSUE TITLE
Unable to install/remove plugins after an upgrade 1.7.5->1.8.0

### ISSUE THREAD

**Issue by Aeris1One** [YunoHost-Apps/etherpad_mypads_ynh#90]
Just upgraded from master to testing, I never installed mypads, and after the upgrade, the "MyPads" link under "create/open a pad with that name" appeared.

**Comment by Aeris1One** [comment]
Can't install/remove any plugin :/

**Comment by maniackcrudelis** [comment]
Sorry https://github.com/YunoHost-Apps/etherpad_mypads_ynh/blob/testing/scripts/upgrade#L377

**Comment by maniackcrudelis** [comment]
Actually, I fixed twice that issue (while working locally), and the second time was a regression...

**Comment by Aeris1One** [comment]
I reinstalled a backup because I wasn't able to install/remove any plugin after the upgrade.

**Comment by maniackcrudelis** [comment]
So I guess that's an other issue, from the admin panel you weren't able to deal with the plugins ?

**Comment by maniackcrudelis** [comment]
I do have that issue as well. It works with the version 1.7.5, it doesn't anymore after an upgrade to 1.8.0
I opened an issue on etherpad repo about that. https://github.com/ether/etherpad-lite/issues/3810

**Comment by Aeris1One** [comment]
Plugins are working if I directly install 1.8 without upgrading.
I saved the MySQL database, deleted etherpad 1.7.5, reinstalled etherpad 1.8, applied MySQL backup.
Maybe you could make a full reinstall in upgrade (saving db, plugins folder,... then reinstalling and restoring things saved before)

**Comment by maniackcrudelis** [comment]
Working on it.
I test different situations.

**Comment by maniackcrudelis** [comment]
Without the non help of the main dev of etherpad, who just consider you should git pull and solve the issues you will surely have... What a great way to provide an app to your users...

I may finally have found the issue, not sure considering that I don't know why I didn't work in the first place.
At least with that fix, I did not reproduce anymore.

At least, we learned something... If you have an issue with etherpad, do not lost your time asking for support on the repo...
