### ISSUE TITLE
Config Panel not working with multi-instance

### ISSUE THREAD

**Issue by Aeris1One** [YunoHost-Apps/etherpad_mypads_ynh#92]
I've etherpad-mypads__2 and etherpad-mypads__3 but no etherpad-mypads.
I used the config panel to change some config (override settings.json and override nginx config) but a error occurred "Application etherpad_mypad is not found".
If I've some times I'll propose a PR.

**Comment by Tagadda** [comment]
This should have been fixed by https://github.com/YunoHost/issues/issues/1544.

**Comment by maniackcrudelis** [comment]
Indeed, it has been fixed or is on its way.
