### ISSUE TITLE
Force update of ep_spellcheck to >= 0.0.7

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost-Apps/etherpad_mypads_ynh#96]
To be honest, I have no idea exactly how etherpad_mypads_ynh behaves about plugin updates.

But this issue to warn that ep_spellcheck 0.0.6 have a bug resulting in certain pads stuck in a refresh-loop forever.

https://github.com/ether/etherpad-lite/issues/3838

0.0.7 fixes it.

**Comment by maniackcrudelis** [comment]
An upgrade of the package itself should update the plugins.
I can't test unfortunately because a newly installed etherpad does install the version 0.0.7 already.

**Comment by ericgaspar** [comment]
Should be fixed with #104
