### ISSUE TITLE
upgrade the obsolete install script

### ISSUE THREAD

**Issue by webafrancois** [YunoHost-Apps/etherpad_mypads_ynh#98]
When I install the etherpad_mypads apps on the dev test yunohost 3.8.1.1 testing version, with the 1.7.5~ynh2 install version, I had a warning message :

> /!\ Packagers! This app is still using the skipped/protected/unprotected_uris/regex settings which are now obsolete and deprecated... Instead, you should use the new helpers 'ynh_permission_{create,urls,update,delete}' and the 'visitors' group to initialize the public/private access. Check out the documentation at the bottom of yunohost.org/groups_and_permissions to learn how to use the new permission mechanism.

I don't know where are the regex settings in the script (in the chown ?), but I would like to  report it here.

**Comment by ericgaspar** [comment]
Closing. New permission system added with #131
